language: python
python:
  - "2.7"
  # - "3.5"
  - "3.6"
script:
  - pytest testing/ --cov=morphs 
  - pytest notebooks/ --cov=morphs --nbval-lax --current-env --cov-append
after_success:
  - coveralls
sudo: required
cache: pip