language: python
python:
  - "2.7"
  # - "3.5"
  - "3.6"
script:
  - pytest -v testing/ --cov=morphs 
  - pytest -v notebooks/1.* --cov=morphs --nbval-lax --current-env --cov-append
  - pytest -v notebooks/2.* --cov=morphs --nbval-lax --current-env --cov-append
  # - pytest -v notebooks/3.* --cov=morphs --nbval-lax --current-env --cov-append
  - pytest -v notebooks/3.* --cov=morphs --nbval-lax --current-env --cov-append
  - pytest -v notebooks/4.* --cov=morphs --nbval-lax --current-env --cov-append
  - pytest -v notebooks/5.* --cov=morphs --nbval-lax --current-env --cov-append
  - pytest -v notebooks/6.* --cov=morphs --nbval-lax --current-env --cov-append
  - pytest -v notebooks/7.* --cov=morphs --nbval-lax --current-env --cov-append
  - pytest -v notebooks/8.* --cov=morphs --nbval-lax --current-env --cov-append
  - pytest -v notebooks/supplemental --cov=morphs --nbval-lax --current-env --cov-append
before_install:
  - sudo apt-get install libav-tools
after_success:
  - coveralls
sudo: required
cache: pip